# Generated by Django 4.2.10 on 2024-02-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_recipes_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='recipes',
            name='author',
            field=models.IntegerField(),
        ),
    ]
